/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StateRouteImport } from './routes/state'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrincipalRouteImport } from './routes/principal'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as InterventionsRouteImport } from './routes/interventions'
import { Route as EarlyWarningsRouteImport } from './routes/early-warnings'
import { Route as DistrictRouteImport } from './routes/district'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIdRouteImport } from './routes/student.$id'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StateRoute = StateRouteImport.update({
  id: '/state',
  path: '/state',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipalRoute = PrincipalRouteImport.update({
  id: '/principal',
  path: '/principal',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const InterventionsRoute = InterventionsRouteImport.update({
  id: '/interventions',
  path: '/interventions',
  getParentRoute: () => rootRouteImport,
} as any)
const EarlyWarningsRoute = EarlyWarningsRouteImport.update({
  id: '/early-warnings',
  path: '/early-warnings',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictRoute = DistrictRouteImport.update({
  id: '/district',
  path: '/district',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIdRoute = StudentIdRouteImport.update({
  id: '/student/$id',
  path: '/student/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/district': typeof DistrictRoute
  '/early-warnings': typeof EarlyWarningsRoute
  '/interventions': typeof InterventionsRoute
  '/notifications': typeof NotificationsRoute
  '/principal': typeof PrincipalRoute
  '/settings': typeof SettingsRoute
  '/state': typeof StateRoute
  '/teacher': typeof TeacherRoute
  '/student/$id': typeof StudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/district': typeof DistrictRoute
  '/early-warnings': typeof EarlyWarningsRoute
  '/interventions': typeof InterventionsRoute
  '/notifications': typeof NotificationsRoute
  '/principal': typeof PrincipalRoute
  '/settings': typeof SettingsRoute
  '/state': typeof StateRoute
  '/teacher': typeof TeacherRoute
  '/student/$id': typeof StudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/district': typeof DistrictRoute
  '/early-warnings': typeof EarlyWarningsRoute
  '/interventions': typeof InterventionsRoute
  '/notifications': typeof NotificationsRoute
  '/principal': typeof PrincipalRoute
  '/settings': typeof SettingsRoute
  '/state': typeof StateRoute
  '/teacher': typeof TeacherRoute
  '/student/$id': typeof StudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/district'
    | '/early-warnings'
    | '/interventions'
    | '/notifications'
    | '/principal'
    | '/settings'
    | '/state'
    | '/teacher'
    | '/student/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/district'
    | '/early-warnings'
    | '/interventions'
    | '/notifications'
    | '/principal'
    | '/settings'
    | '/state'
    | '/teacher'
    | '/student/$id'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/district'
    | '/early-warnings'
    | '/interventions'
    | '/notifications'
    | '/principal'
    | '/settings'
    | '/state'
    | '/teacher'
    | '/student/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRoute
  DistrictRoute: typeof DistrictRoute
  EarlyWarningsRoute: typeof EarlyWarningsRoute
  InterventionsRoute: typeof InterventionsRoute
  NotificationsRoute: typeof NotificationsRoute
  PrincipalRoute: typeof PrincipalRoute
  SettingsRoute: typeof SettingsRoute
  StateRoute: typeof StateRoute
  TeacherRoute: typeof TeacherRoute
  StudentIdRoute: typeof StudentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/state': {
      id: '/state'
      path: '/state'
      fullPath: '/state'
      preLoaderRoute: typeof StateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principal': {
      id: '/principal'
      path: '/principal'
      fullPath: '/principal'
      preLoaderRoute: typeof PrincipalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interventions': {
      id: '/interventions'
      path: '/interventions'
      fullPath: '/interventions'
      preLoaderRoute: typeof InterventionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/early-warnings': {
      id: '/early-warnings'
      path: '/early-warnings'
      fullPath: '/early-warnings'
      preLoaderRoute: typeof EarlyWarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/district': {
      id: '/district'
      path: '/district'
      fullPath: '/district'
      preLoaderRoute: typeof DistrictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/$id': {
      id: '/student/$id'
      path: '/student/$id'
      fullPath: '/student/$id'
      preLoaderRoute: typeof StudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRoute,
  DistrictRoute: DistrictRoute,
  EarlyWarningsRoute: EarlyWarningsRoute,
  InterventionsRoute: InterventionsRoute,
  NotificationsRoute: NotificationsRoute,
  PrincipalRoute: PrincipalRoute,
  SettingsRoute: SettingsRoute,
  StateRoute: StateRoute,
  TeacherRoute: TeacherRoute,
  StudentIdRoute: StudentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
